[package]
authors = [
  "spyophobia <76800505+spyophobia@users.noreply.github.com>",
]
description = "A desktop GUI frontend for shadowsocks-rust client implemented with gtk-rs."
edition = "2021"
name = "shadowsocks-gtk-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
gtk = "0.14.3"
# itertools = "0.10.1"
libappindicator = "0.6.1"
log = "0.4.14"
# regex = "1.5.4"
crossbeam-channel = "0.5.1"
nix = "0.23.0"
serde = {version = "1.0.130", features = ["derive"]}
serde_yaml = "0.8.21"
simple_logger = "1.13.0"
