[package]
edition = "2018"
name = "shadowsocks-druid"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
druid = "0.7.0"
itertools = "0.10.1"
log = "0.4.14"
regex = "1.5.4"
simple_logger = "1.13.0"
