name: Auto compile test

on:
  pull_request:
    branches:
      - master
      - dev # mainly for dependabot
  push:
    branches:
      - master
      - dev
      - cicd
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Add PPA for dependencies
        # See https://askubuntu.com/a/1093251/1020143
        run: sudo add-apt-repository ppa:paulo-miguel-dias/mesa
      - name: Update system
        run: sudo apt update && sudo apt upgrade
      - name: Install dependencies
        run: sudo apt install libappindicator3-dev libgtk-3-dev
      - name: Build default (release)
        run: cargo build --release --verbose
      - name: Build without default features (release)
        run: cargo build --release --no-default-features --verbose
  #   - name: Run tests
  #     run: cargo test --release --verbose
