name: Auto compile test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - dev
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Rust cache
      uses: Swatinem/rust-cache@v1
    - name: Setup & cache dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: libappindicator3-dev libatk1.0-dev libgtk-3-dev libpango1.0-dev
        refresh: true
    - name: Build release
      run: cargo build --release --verbose
 #   - name: Run tests
 #     run: cargo test --release --verbose
