name: Release new version

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test build the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install dependencies
        run: sudo apt install libappindicator3-dev libgtk-3-dev
      - name: Test build
        run: cargo build --release --verbose
  publish-crates-io:
    name: Publish code to crates.io
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install dependencies
        run: sudo apt install libappindicator3-dev libgtk-3-dev
      - name: Publish to crates.io
        uses: katyo/publish-crates@v1
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
            dry-run: true
  # TODO: Github release
  
